### ISSUE TITLE
Shouldn’t empty visibleIf hide the widget

### ISSUE THREAD

**Issue by thereiskeks** [makinacorpus/angular2-schema-form#102]
I want to hide some widgets. I find the behaviour unexpected that a widget is shown if i pass an empty condition object.

### Example:
```json
    "registerNewsletter": {
        "type": "boolean",
        "description": "I want to receive the newsletter",
        "default": false,
         "visibleIf": { }
      }
```
Is there another way to hide a widget? Is there any interest that i build this?

**Comment by ebrehault** [comment]
If you have a use case for that, I guess other people might have a similar need, so sure, implement it.

**Comment by fbessou** [comment]
Maybe adding a new keyword in the schema would be more elegant:
```
{
  type: "boolean",
  default: false,
  hidden: true,
  ...
}
```
But it could be even easier to add a 'hidden' widget. So you could declare a hidden field like this:
```
{
  type: "boolean",
  default: "false",
  widget: "hidden",
  ...
}
```

**Comment by thereiskeks** [comment]
Declaring a hidden widget works, but visibleIf also removes the Object from the model value. And I need that behavior. 

And I'd rather use the already established "visibleIf" flag instead of adding a new one. That seems simpler and more logical for me. If a line is added to the documentation, it should be quite clear.
