### ISSUE TITLE
Action binding & Model binding doesn't work

### ISSUE THREAD

**Issue by acidline** [makinacorpus/angular2-schema-form#110]
Hi,

Thank's for your work on this project.

I encounter some problems with your documentation. According to the doc, binding model & actions are very simple : 
```javascript
@Component({
template: '<sf-form [schema]="mySchema" [model]="myModel"></sf-form>'
})
export class AppComponent {

  mySchema ={
    "properties": {
      "email": {
        "type": "string",
        "description": "email",
        "format": "email"
      }
    }
  }

  myModel = {
    email:" john.doe@example.com"
  }

}
```
This piece of code doesn't work. The myModel property is bind but doesn't appear in form render.

It's exactly the same with "actions" : 

```javascript
@Component({
  selector:"minimal-app",
  template: '<sf-form [schema]="mySchema" [actions]="myActions"></sf-form>'
})
export class AppComponent {

  mySchema = {
    "properties": {
      "email": {
        "type": "string",
        "description": "email",
        "format": "email"
      }
    },
    "buttons": [{
      "id": "alert", // the id of the action callback
      "label": "Alert !" // the text inside the button
    }]
  }

  myActions = {
    "alert": (property) => {alert(JSON.stringify(property.value))}
  }
}
```

It doesn't work, alert is never trigger !

Can you explain the correct implementation of this component parts ?
Thank's by anticipation.

Nicolas

**Comment by ebrehault** [comment]
You need to provide the DefaultWidgetRegistry:
```providers: [{ provide: WidgetRegistry, useClass: DefaultWidgetRegistry }]```
(in your component or in your module)

**Comment by acidline** [comment]
The DefaultWidgetResgitry is already provided in my SharedModule.
The registry is normaly reachable.

Thx for your help.

**Comment by ebrehault** [comment]
And does it work if you provide it directly in your component? (just to try)

**Comment by acidline** [comment]
It's the same. 

I will try to install your demo and make others tests.
We keep in touch.

**Comment by acidline** [comment]
Do you have a repo for this "working" demo ?
https://makinacorpus.github.io/angular2-schema-form/#/playground

**Comment by ebrehault** [comment]
What you see here: https://makinacorpus.github.io/angular2-schema-form/#/playground is the ./tests project contained in this repository (here: https://github.com/makinacorpus/angular2-schema-form/tree/master/tests ).
If you want to build it, you can refer to the install section of the Travis config:
https://github.com/makinacorpus/angular2-schema-form/blob/master/.travis.yml#L17
and then:
```
cd tests/src/app && cp -r ../../../src/ ./lib && cd ../..
ng serve
```

**Comment by acidline** [comment]
It's works great with the "tests" folder.

My problem seems similar to this comment [#111](https://github.com/makinacorpus/angular2-schema-form/issues/111)

I read my JSON config from API. If I wrote my config directly in my component, it works correctly.

Do you have any suggestions ?

**Comment by ebrehault** [comment]
I confirm it is possible to load your schema or model from an API, I do that all the time, like here:
https://github.com/plone/plone.restapi-angular/blob/master/src/views/edit.ts#L45
Nevertheless, you need to make sure your initial schema (before the API call is successful) is not empty, like here:
https://github.com/plone/plone.restapi-angular/blob/master/src/views/edit.ts#L26

**Comment by fbessou** [comment]
I suppose you can also display the form only when all the data is fetched (with an *ngIf for example).

**Comment by jrymer** [comment]
I was having the same issue as acidline where writing JSON config directly in the component worked, but getting the JSON from API was not working. I was unable to see buttons when getting JSON from API but was able to see buttons if writing JSON directly to component.

> Nevertheless, you need to make sure your initial schema (before the API call is successful) is not empty, like here:
https://github.com/plone/plone.restapi-angular/blob/master/src/views/edit.ts#L26


Initializing the schema with buttons renders them on forms from the API, but is there any way to get the JSON from the API to render the buttons? Ideally I have nothing hardcoded.

`public schema = {
    'properties': {},
    'buttons': [
      { id: 'submit', label: 'Submit' }
    ]
  };`

This works but buttons will not render if I exclude the buttons from the initialization.

**Comment by ebrehault** [comment]
@jrymer I agree it looks like a bug, but anyway you still have to hardcode the different actions implementation (as your JSON will obviously not send you back chuncks of Javascript).

**Comment by jrymer** [comment]
@ebrehault Good point, for now initializing the schema with buttons works and the actions still work with them. Thanks.

**Comment by acidline** [comment]
@ebrehault @jrymer Yes, it's work correctly with the initialisation actions.
It will be a good enhancement to specify this part in the doc !

Thanks for your time.

**Comment by ebrehault** [comment]
@acidline ... or to support empty actions at init time :)
Either way, PRs are welcome :)
