### ISSUE TITLE
Removing first item in type array not working as expected

### ISSUE THREAD

**Issue by artonio** [makinacorpus/angular2-schema-form#114]
Test Schema:

```{
    "properties": 
    {
            "users": {
            "type": "array",
            "description": "",
            "title": "Users",
            "items": {
                "type": "object",
                "dswaPath": ["lastName"],
                "properties": {
                    "lastName": {
                        "type": "string",
                        "description": "Last name",
                        "minLength": 2,
                        "maxLength": 30
                    },
                    "firstName": {
                        "type": "string",
                        "description": "First name",
                        "minLength": 2,
                        "maxLength": 30
                    }
                },
                "fieldsets": [
                    {
                        "id": "fieldset-default",
                        "title": "Users",
                        "fields": [
                            "lastName",
                            "firstName"
                        ]
                    }
                ]
                
                

                }
            }
    },
    "buttons": [{
		"label": "Alert",
		"id": "alert"
	},
	{
		"label": "Reset",
		"id": "reset"
	}]
}

```

1. Add two users. 
2. set User 1 first name to: John
3. set User 2 first name to: Bob
4. Click Remove Button under the first user

Expected result: Only user Bob will remain
Actual result: user John remained

Tested by cloning from master and using "tests" directory.

**Comment by marc101101** [comment]
Same problem. This is a real bug

**Comment by marc101101** [comment]
This line is wrong:
`<div *ngFor="let itemProperty of formProperty.properties; let i=index; trackBy:trackByIndex">`

You have to write:
`<div *ngFor="let itemProperty of formProperty.properties; let i=index; trackBy:trackByIndex(i,itemProperty)">`
Or you omitt trackByIndex. Should work too.

**Comment by camille68** [comment]
Facing same issue: the last item is removed instead of the first one.

**Comment by ejmvar** [comment]
Same here.
At demo page, the steps are:
- add three items to the ARRAY,
- delete any item,
- no matter what item was deleted, the model is updated correctly
- BUT the array ALWAYS displays all original items MINUS the last one in the array

This way, MODEL DATA is correct, BUT the user sees wrong data
Once the display is updated (moving back and forth, or forward and back again), the display shows (CORRECTLY) the data stored in the model.

So, it's behaviour in incorrect only at displaying the updated values of the array.

I'm a newbie here, and cannot interpret how could I refresh whithout the mentioned movement under the DemoCustomWidget.

This is an awesome implementation.
I would love to understand how to solve this.

And, of course, Thanks for such an amazing project.

(Eduardo)

**Comment by ebrehault** [comment]
Fixed using the @marc101101 solution. Thanks! Note: next time, make directly a pull request :)
