### ISSUE TITLE
Force rerendering of the form?

### ISSUE THREAD

**Issue by shral** [makinacorpus/angular2-schema-form#12]
Is there possible to force re rendering of the form, I want to make possible to use multiple schemas, so I can switch them on button click or something like that.

**Comment by shral** [comment]
I found in the meantime a "solution" or more like a workaround:
```
// In the template
<schema-form *ngIf="showschema"  [schema]="schema" [validators]="validators" (onChange)="val=$event.value"></schema-form>

//In the component
private showschema = true;
...
	reloadForm(){
		this.showschema = false;
		setTimeout(()=>{
			this.showschema = true;
		},0);
	}
```

**Comment by fbessou** [comment]
Updating the `schema` input reference should also work. If you just want to modify an existing schema, without making a deep copy you can also trigger a change detection after your modification using ChangeDetectorRef's detectChanges method.
