### ISSUE TITLE
Cannot determine module for ButtonWidget

### ISSUE THREAD

**Issue by jrymer** [makinacorpus/angular2-schema-form#122]
In package.json 
`"angular2-schema-form": "^1.0.0-beta.7",`

`npm list` yields ` angular2-schema-form@1.0.0-beta.9`

I destroyed my node modules. After `npm install` and then `npm start` I get the following error.

`ERROR in Cannot determine the module for class ButtonWidget in /Users/joshuarymer/workspaces/gmm/gmm-ui/node_modules/angular2-schema-form/dist/defaultwidgets/button/button.widget.d.ts! Add ButtonWidget to the NgModule to fix it.`

Also tried `npm install angular2-schema-form --save`

Node v7.4.0
npm 4.0.5
Angular CLI 1.3.0
Angular 4.3.4

**Comment by enavarro222** [comment]
Got the same issue with last release.

**Comment by jrymer** [comment]
I tried your above fix, did it work for you?

**Comment by enavarro222** [comment]
@jrymer yep it work

**Comment by enavarro222** [comment]
@jrymer You can also force npm to use the version "1.0.0-beta.7", juste remove the `^` in package.json:
```
"angular2-schema-form": "1.0.0-beta.7",
```

**Comment by jrymer** [comment]
@enavarro222 I reverted back to 1.0.0-beta.7 when I realized the issue was with latest.

I'm new to this so out of curiosity, how were you able to modify the `module.ts`? I was only able to see js files. Did you fork the repo and edit there? Can this not be done directly in `node_modules`?

**Comment by enavarro222** [comment]
@jrymer with `npm install` you only get compiled js. So to edit ts files you need to clone the repo and compile it "by hand".

In ./node_modules:
```
$ rm -rf angular2-schema-form/
$  git clone git@github.com:makinacorpus/angular2-schema-form.git
$ cd  angular2-schema-form/
$ ## Edit what you need
$ npm install              # install angular2-schema-form dep
$ npm run build            # build it
```

**Comment by jrymer** [comment]
Thanks, appreciate the quick lesson.
