### ISSUE TITLE
Validation of fieldsets

### ISSUE THREAD

**Issue by ralph-hm** [makinacorpus/angular2-schema-form#134]
Hey,

it is possible to check whether my whole form is valid or not, but is it possible to check if parts of my form are valid? For example i need to check, if specific fieldsets are valid to implement a wizard component.

Thanks!

**Comment by ralph-hm** [comment]
It was easier than i expected.

```
isValid(fields: string[]): boolean {
    for (let field of fields) {
      if (!this.formProperty.properties[field].valid) {
        return false;
      }
    }
    return true;
  }
```

**Comment by aaronhong** [comment]
@ralph089 thanks for your answer. I'm new to ngx-schema-form. Where are you using this `isValid()` function and how did you pass the fields to it? Could you give a more extended answer. Thanks.
