### ISSUE TITLE
more fields in a row

### ISSUE THREAD

**Issue by mixxr** [makinacorpus/angular2-schema-form#14]
by using the schema (as below):
`"fieldsets": [{
		"fields": ["student"],
		"title": "Student"
	}, {...`
the fields of student are showed 1 field per row: 

- row#1) firstname 
- row#2) lastname
- row#3) id
- and so on

is there a way to render the form in a different way like (2 fields x row):
- row#1) firstname, lastname
- row#2) id, age

it could be nice if bootstrap col classes were supported like:
- row#1) firstname(col-xs-6), lastname(col-xs-6)
- row#2) id(col-xs-4), age (col-xs-8)

thanks

**Comment by ebrehault** [comment]
We do plan to allow to provide a custom layout for a form but it is not possible for now.
