### ISSUE TITLE
cant submit data to backend server

### ISSUE THREAD

**Issue by stephenlane** [makinacorpus/angular2-schema-form#141]
Hi There,

I cant submit data to my backend server as I cant access "this" from within "myActions" which is were by button functions are. Any help is much appreciated.

Thanks,

Stephen

**Comment by ebrehault** [comment]
You probably need to bind the methods to `this`. Something like this:
```
this.actions = {
      save: this.onSave.bind(this),
      cancel: this.onCancel.bind(this)
    };
```

**Comment by stephenlane** [comment]
okay so that half works for me, how do I access the form this way ...

**Comment by stephenlane** [comment]
figured it out thanks 


this.actions = {
      save: this.onSave.bind(this),
      cancel: this.onCancel.bind(this)
    };


onSave(form){
  console.log(form)
}

**Comment by JianhuisHuang** [comment]
is possible support without widget and as normal button ? like this png 
![image](https://user-images.githubusercontent.com/46215903/57770279-85ed9e80-7742-11e9-87c4-4b3e7ba4de2c.png)
