### ISSUE TITLE
disable form fields

### ISSUE THREAD

**Issue by stephenlane** [makinacorpus/angular2-schema-form#142]
Hi there,

Just wondering is it possible to disable an entire form or fields within the form.

Thanks,

Stephen

**Comment by ebrehault** [comment]
Something like this will work:
```
Object.keys(this.schema.properties).map(prop => {
      this.schema.properties[prop].readOnly = true;
    });
```
I have added an example here: https://github.com/makinacorpus/angular2-schema-form/blob/master/tests/src/app/app.component.ts#L124

**Comment by stephenlane** [comment]
thank you, I found a different solution

`  <fieldset [disabled]="true">
        <sf-form [schema]="resultsNEW"></sf-form>  
      </fieldset>`
