### ISSUE TITLE
Generate a form partially

### ISSUE THREAD

**Issue by ralph-hm** [makinacorpus/angular2-schema-form#143]
I'm curious if it's possible to generate not the whole form, but only parts.

In my case, i've got a complex JSON-Schema, but most of the time, the values change only on a few places. So it would be good, if i could specify which fields to render to simplify things. On the same time, the user should be able to switch to the complex form, where he can see the whole form.

Is there an easy way to do this? Or should i implement two schemas and patch the simplified one into the complex one with an onChange listener?

**Comment by ebrehault** [comment]
It seems pretty easy to change the schema the way you want.
Let's say you create the full schema and you add an extra attribute to define if a field belongs to the complex form or the simple one.
And depending on the context you will filter out complex form's fields or not.

**Comment by ralph-hm** [comment]
This seems actually pretty easy and should do the trick. I like that solution. Thank you! :)
