### ISSUE TITLE
Empty _updateValue function in atomicProperty.ts file

### ISSUE THREAD

**Issue by glennverschooren** [makinacorpus/angular2-schema-form#148]
Is there a reason why the _updateValue function in the atomicProperty.ts file is empty?
https://github.com/makinacorpus/angular2-schema-form/blob/b59cf8568f446820dee301ba9d310695a751905c/src/model/atomicproperty.ts#L32

The function is called here: https://github.com/makinacorpus/angular2-schema-form/blob/b59cf8568f446820dee301ba9d310695a751905c/src/model/formproperty.ts#L81

**Comment by ebrehault** [comment]
AtomicProperty is an abstract class, this method is implemented by classes which extends AtomicProperty, like here:
https://github.com/makinacorpus/angular2-schema-form/blob/4722efe2a0afcc6b8c67a20e4e8d3ccce5bb95f4/src/model/objectproperty.ts#L59
