### ISSUE TITLE
$ref does not work

### ISSUE THREAD

**Issue by jh-code** [makinacorpus/angular2-schema-form#15]
Trying to use this data to create a form and I get the following error:

`ORIGINAL EXCEPTION: Undefined type undefined`

If I copy the properties from the registers definition into the registers property, it displays the input just fine. Is this not supported or am I doing it wrong?

    {
        "title": "Device Template",
        "definitions": {
            "registers": {
                "type": "object",
                "properties": {
                    "perm": {
                        "type" : "string"
                    }
                }
            }
        },
        "type": "object",
        "properties": {
            "deviceaddr": {
                "description": "Device Address",
                "type": "string"
            },
            "registers": { "$ref": "#/definitions/registers" }
        },
        "required": [ "deviceaddr" ]
    }

**Comment by ebrehault** [comment]
Sorry, it is not supported for now.

**Comment by estradamarkie** [comment]
is there a work-around to this?

**Comment by ebrehault** [comment]
yes, sure, see https://github.com/makinacorpus/angular2-schema-form/issues/8#issuecomment-257853250

actually, any kind of pre-processing is possible (you might for instance compse your schema from different AJAX call, you can reorganize the fields, etc.)
