### ISSUE TITLE
Support for multiple select?

### ISSUE THREAD

**Issue by GFoley83** [makinacorpus/angular2-schema-form#151]
Hi there,

just wondering if there's an approach I've missed for storing multiple select values? 
If tried using `anyOf` instead of `oneOf` but the default widget doesn't support that.

I'd be will to do a PR if you've got ideas on what a solution might look like.

**Comment by ebrehault** [comment]
I guess you can derivate quite easily the SelectWidget https://github.com/makinacorpus/angular2-schema-form/blob/master/src/defaultwidgets/select/select.widget.ts

The reason we do not have multiselect for now is just regular HTML select multiple are bad UI, so it is usually better to use checkboxes (which already exist) or an addon like chosen or select2 (but as it implies a specific dependency, it is better to handle it in a separate package rather in core).

**Comment by aaronhong** [comment]
@ebrehault thanks for your comment. It's helpful.

So what I understand is that by default checkboxes support multiple select. However, what kind of confuses me is that [checkboxes also use `oneOf`](https://github.com/guillotinaweb/ngx-schema-form/blob/master/projects/schema-form/src/lib/defaultwidgets/checkbox/checkbox.widget.ts#L19). So it seems like `oneOf` is not actually used semantically for "only one of these options," but it is used more for a way to enumerate options. Whether you could only choose one of them or many of them is irrelevant. Is that correct?

**Comment by ebrehault** [comment]
yes correct, by choosing the widget checkbox we consider we want to allow multiple values (if that was not the case, we would pick radio widget)
