### ISSUE TITLE
css

### ISSUE THREAD

**Issue by stephenlane** [makinacorpus/angular2-schema-form#154]
Hi there,

Is it possible to add css to the form?

Regards,

Stephen

**Comment by ebrehault** [comment]
You can either do that in your main styles.css file, or add some CSS to your component which contains the form and make sure it is not encapsulated.

**Comment by stephenlane** [comment]
is it possible to add an element so that I can style this.

e.g. show 3 text fields then add in a <hr /> element?

**Comment by daniele-pecora** [comment]
I would recommend to write your own widget and use a custom registry as described in [creating-a-custom-widget](https://github.com/makinacorpus/angular2-schema-form#creating-a-custom-widget)

**Comment by daniele-pecora** [comment]
@ebrehault would you mind to close this?

**Comment by ebrehault** [comment]
right
