### ISSUE TITLE
Cannot make production builds on angular-cli with Angular5

### ISSUE THREAD

**Issue by dmastag** [makinacorpus/angular2-schema-form#161]
There is an instance of Subject that is imported directly making it not possible to do production builds.
I made 2 Pull requests that should fix that, kindly review and merge.

https://github.com/makinacorpus/angular2-schema-form/pull/159
https://github.com/makinacorpus/angular2-schema-form/pull/160

**Comment by dmastag** [comment]
@ebrehault thanks for the merge
Would appreciate if a new release could be published so that I can upgrade my App to ng5

**Comment by ebrehault** [comment]
Done! 1.1.0 is released :)

**Comment by dmastag** [comment]
Thanks and its working as expected.
Closing this now
