### ISSUE TITLE
Two way binding of model input

### ISSUE THREAD

**Issue by wurmrobert** [makinacorpus/angular2-schema-form#163]
Hy. 

I would like to use the [model] input with two way binding [(model)]. I know that there is the onChange output but i think it would be much more nicer if i could just use two way binding. 

Are there any plans to implement this feature?

As a workaround until yet i have build a wrapper component.

```
@Component({
	selector: 'uni-sf-form',
	template: `
		<sf-form  [schema]="schema" [model]="model" (onChange)="onSchemaChanged($event)"></sf-form>
	`
})
export class UniSfFormComponent {

	@Input() schema: OogleJsonSchema;
	@Input() model: any;
	@Output() modelChanged = new EventEmitter();
	@Output() onChange = new EventEmitter();

	onSchemaChanged(e: any) {
		
		if (this.model) {
			Object.assign(this.model, e.value);
		} else {
			this.model = e;
		}		
		this.modelChanged.emit(e); // create two way binding

		this.onChange.emit(e);
	}
 }
```

**Comment by ebrehault** [comment]
Well, two-way data-binding sounds risky in that case (regarding performances), but if you want to implement it, I guess we will merge it (and people will be free to use at their own risks).

**Comment by sunew** [comment]
closing, since PR is merged
