### ISSUE TITLE
Allow providing SchemaValidatorFactory 2 - FormComponent

### ISSUE THREAD

**Issue by daniele-pecora** [makinacorpus/angular2-schema-form#173]
The provided SchemaValidatorFactory via the module providers is not being used in FormComponent,
since the SchemaValidatorFactory is explicitly set to ZSchemaValidatorFactory.

To make it work, the declaration of the SchemaValidatorFactory must be removed from the providers, since it is already declared as global provider in `schema-form.module.ts`.

So then the declaration in `form.component.ts` should be changed from ...
```javascript
  providers: [
    ActionRegistry,
    ValidatorRegistry,
    SchemaPreprocessor,
    WidgetFactory,
    {
      provide: SchemaValidatorFactory,
      useClass: ZSchemaValidatorFactory
    }, {
      provide: FormPropertyFactory,
      useFactory: useFactory,
      deps: [SchemaValidatorFactory, ValidatorRegistry]
    },
    TerminatorService,
  ]
```
... to this
```
  providers: [
    ActionRegistry,
    ValidatorRegistry,
    SchemaPreprocessor,
    WidgetFactory,
    {
      provide: FormPropertyFactory,
      useFactory: useFactory,
      deps: [SchemaValidatorFactory, ValidatorRegistry]
    },
    TerminatorService,
  ]
```

So then the `SchemaFormModule` in your module called with `forRoot()` will make it possible to set you custom validator factory.

e.g
```javascript
imports: [
    ...
    // schema form module
    , SchemaFormModule.forRoot()
   ...
  ],
```
This issue is based on the changes made in 
https://github.com/makinacorpus/angular2-schema-form/commit/2621a394e174914cec58efa3d8e012e17fa2f036

**Comment by rumpl** [comment]
Hey,

Could you guys make a new release please? I need this one so bad :)

Thanks

**Comment by ebrehault** [comment]
@rumpl 1.2.0 is released, happy new year :)

**Comment by rumpl** [comment]
Great gift for the start of the year, thanks! 

Happy new year!
