### ISSUE TITLE
trouble to fork and use module

### ISSUE THREAD

**Issue by couturierb** [makinacorpus/angular2-schema-form#176]
Hi !

I'am trying to clone and develop into angular2-schema-form module. I can build the project (npm install, install:peers and build), but when i want to use it (using npm link or directly import from file path), i have this error :

> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in <file_path>/angular2-schema-form/node_modules/@angular/core/core.d.ts, resolving symbol SchemaFormModule in <file_path>/angular2-schema-form/dist/schema-form.module.d.ts, resolving symbol SchemaFormModule in <file_path>/angular2-schema-form/dist
> /schema-form.module.d.ts

When i just use the this module by npm install, it works well, but i need to doing some changes.
Any idea ?

Thansk !

**Comment by ebrehault** [comment]
When you `npm link` in another project, the node_modules folder from your angular2-schema-form install is discovered by the compiler and it pollutes it.

An easy fix is to remove your node_modules folder in angular2-schema-form.

A more solid approach is explained here: https://github.com/angular/angular-cli/issues/6195#issuecomment-335861439

**Comment by couturierb** [comment]
Hi,

I understand better now, thanks a lot for your quick reply !
I finally add 'angular2-schema-form' as a module of my project and it works.

Thanks again !
