### ISSUE TITLE
Nested object 'required' errors on missing properties not applied

### ISSUE THREAD

**Issue by ccordenier** [makinacorpus/angular2-schema-form#178]
The following line of code returns an undefined 'prop' element in case of nested object validation:

https://github.com/makinacorpus/angular2-schema-form/blob/03a708cb877a89b43cbba83dfb7d1bc5e6b3fd04/src/model/objectproperty.ts#L68

This is due to the fact that the searchProperty is done from the root, but as validation is done partially on every property, for object properties, search properties algorithm in error should be done relatively to the object itself and not the document root.

Path returned by ZSchema start with "#/" in case of object property validation. The consequence is that the code of propertyobject.runValidation only work for the first level object.

I still don't know what's the best option to solve this issue, but keep you informed.

**Comment by ccordenier** [comment]
Replaced a searchProperty  by a getProperty... and seems to work with nested objects.

At least, it makes sense to read property instead of search property in the PropertyGroup hierarchy.

**Comment by ccordenier** [comment]
After digging more in the validation algorithm, I think the main problem with validation, is that it's run multiple times for the same property. At the object level and at each property level, not always in the same order. And given the path resolution problem, errorMessages of ControlWidget is 'often' not appropriate and vary a lot regarding which field has already been filled.

**Comment by ccordenier** [comment]
Finally, an ultimate question : Why don't we run validation only at the root level at least for JSON schema validation ? I saw in the debug that the JSON schema made once on the root element returns all the schema errors with the valid path from the root.

Am I missing something ?

**Comment by ebrehault** [comment]
When we implement a wizard form where the user moves from a fieldset to another, it is useful to be able to display the current fieldset errors only.

**Comment by ccordenier** [comment]
I absolutely agree with the need. But I think validating schema from the root will not prevent from having this feature. By default z-schema stop at the first error, but there is an option to continue. In that case, the whol schema is validated, and all the property paths are from the root.

https://github.com/zaggino/z-schema#breakonfirsterror

The fact is that modifying a property deep in the object hierarchy will bubble up to the root. And validation is made at every stage.

Another problem, is that validation is that use case:

Let's say we have this schema:

> { type: object,
      properties: {
        name: {
          type: string,
          minLength: 10
        }
      }
   }

In the current implementation, without changing anything to the 'name' property (on first load) there will be two JSON Schema validation

"", { type: string, minLength:10} => will fail because the string is not long enough
and
{}, { type: object, properties: {name: {type: string,minLength: 10}}} => will succeed because the name property is not required.

In the end, I like the idea of properties that validates on their own. But at the end it generates side effects due to path resolution on failing properties returned by Z-Schema.

I suggest that AtomicProperty keep on validating on their own for custom validators for efficiency, but keep JSON Schema validation at the root level with the correct option for PropertyGroup.

This design will simplify the overall validation and path resolution as everything start from the root.

**Comment by ebrehault** [comment]
Oh I see! You are right.
If you have time to implement it, please do, we will review your PR (do not hesitate to push a work-in-progress PR if you need some advices about the implementation).

**Comment by ccordenier** [comment]
Of course, If I have time I'll push a PR. Thanks for your approval.

**Comment by Invis1ble** [comment]
Any changes?

**Comment by Invis1ble** [comment]
With `breakOnFirstError` option all works as expected.

**Comment by sunew** [comment]
@Invis1ble where did you apply this option?

**Comment by Invis1ble** [comment]
@sunew on `ZSchema` intantiation, see in my commit.

https://github.com/zaggino/z-schema#breakonfirsterror
https://github.com/zaggino/z-schema/issues/131

**Comment by ebrehault** [comment]
Fixed by https://github.com/makinacorpus/angular2-schema-form/pull/202
