### ISSUE TITLE
Disabling submit button

### ISSUE THREAD

**Issue by rumpl** [makinacorpus/angular2-schema-form#179]
Hello,

First, thank you for this library, I'm playing with it and like it so far.

I have one question though, is it possible to disable a button (like the submit button) if the form is not valid?

Thanks

**Comment by rumpl** [comment]
Ok I just found one solution and would like to put it here for code review if you have the time.

I created a custom component `ButtonWidgetComponent`and it looks like this:
```typescript
import { Component } from '@angular/core';
import { ControlWidget } from 'angular2-schema-form/dist/widget';
import { OnInit, AfterViewInit } from '@angular/core/src/metadata/lifecycle_hooks';

@Component({
  selector: 'app-button',
  template: '<button [disabled]="disabled">Hola</button>'
})
export class ButtonWidgetComponent extends ControlWidget implements OnInit, AfterViewInit {
  disabled = false;

  ngOnInit(): void {
    this.formProperty.errorsChanges.subscribe((errors) => {
      this.disabled = errors != null && errors.length !== 0;
    });
  }

  ngAfterViewInit() { }
}
```
I need to extend `ControlWidget` if I want to have the reference to the `formProperty`.

One thing I don't really like is that I have to implement the `ngAfterViewInit` method so that the `ControlWidget` one doesn't get called because it fails since there is no control really.

What do you think about my solution? Is there a better/cleaner way of doing this?

Chers

**Comment by ebrehault** [comment]
It looks pretty good to me, I have no better suggestion.

**Comment by rumpl** [comment]
Ok no, sorry for the spam, you can just extend the `ButtonWidget`, it has the `formProperty` too.

The code:
```typescript
import { Component } from '@angular/core';
import { OnInit } from '@angular/core/src/metadata/lifecycle_hooks';
import { ButtonWidget } from 'angular2-schema-form';

@Component({
  selector: 'app-button',
  template: '<button [disabled]="disabled" (click)="button.action($event)">{{button.label}}</button>'
})
export class ButtonWidgetComponent extends ButtonWidget implements OnInit {
  disabled = false;

  ngOnInit(): void {
    this.formProperty.errorsChanges.subscribe((errors) => {
      this.disabled = errors != null && errors.length !== 0;
    });
  }
}
```
