### ISSUE TITLE
Cannot find module 'angular2-schema-form'.

### ISSUE THREAD

**Issue by CSchulz** [makinacorpus/angular2-schema-form#18]
I have tried to use the module as described in the README and encountered the issue `Cannot find module 'angular2-schema-form'.`.

It is also tracked for the demo project https://github.com/fbessou/angular2-schema-form-demo/issues/5

I think it could be related to #1 ?

**Comment by ebrehault** [comment]
I have the same problem, but it is quite new (since we upgraded to Angular 2 final, I think).
We will fix that.

**Comment by ebrehault** [comment]
I forgot to mention something: we do get this error message, but the forms are working anyway.

**Comment by CSchulz** [comment]
The demo doesn't work for me:

![image](https://cloud.githubusercontent.com/assets/1520593/19262545/d635623c-8f97-11e6-96f3-bb726d6bece4.png)

And my application doesn't start up with the same error in the console.

**Comment by Vegita2** [comment]
It seems to work if you add an index.d.ts inside the angular2-schema-form module with this line 
```
export * from 'angular2-schema-form/dist/src'
```
or for now you could add this to your type definitions
```
declare module 'angular2-schema-form' {
    export * from 'angular2-schema-form/dist/src'
}
```

**Comment by ebrehault** [comment]
@Vegita2 indeed, you are right. Do you know how the packaging should be done to avoid this problem? (`package.json` contains a `main` attributes to indicates the JS entry point, is there something similar for .d.ts?)

**Comment by ebrehault** [comment]
@Vegita2 we were just missing the `typings` property in `package.json`.

**Comment by aurimukas** [comment]
Still the problem persists. when defining typings you need to change this
`"typings": "dist/index.d.ts"` to this `"typings": "dist/src/index.d.ts"`

**Comment by ebrehault** [comment]
We need to repackage properly the all thing so everything is exposed from root and not from ./src

**Comment by aurimukas** [comment]
@ebrehault agree.. it was just a fast solution to make it work..

**Comment by aurimukas** [comment]
@ebrehault could you list me project building requirements (node versions etc.) because with my current config I can't build it

**Comment by ebrehault** [comment]
Well right now, it is pretty much broken.
I am fighting AoT issues in another package (https://github.com/makinacorpus/angular-traversal), seems like this article https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad gives a good approach.

Once I will have a clean base, I will update angular2-schema-form the same way.
