### ISSUE TITLE
Demo app not working

### ISSUE THREAD

**Issue by marcopolo03** [makinacorpus/angular2-schema-form#182]
Hi, 
demo app is currently not working, I get following error after cloning repo:

`ERROR in /../angular2-schema-form/tests/src/app/app.component.ts (9,8): Cannot find module 'angular2-schema-form'.
ERROR in /../angular2-schema-form/tests/src/app/app.module.ts (6,34): Cannot find module 'angular2-schema-form'.
`

When I change declaration in those 2 files on `import { SchemaFormModule } from './lib';` then the project will be compiled, but will not work anyway - in console can this error be seen: `Error: Unexpected value 'SchemaFormModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`

What am I missing?

**Comment by ebrehault** [comment]
The library code needs to be located in the `tests` project.

There is an npm command which does the job:

```
npm run test:updateLib
cd tests
npm install
ng serve
```
