### ISSUE TITLE
__extends is not defined

### ISSUE THREAD

**Issue by jh-code** [makinacorpus/angular2-schema-form#19]
Using the install instructions, and adding the module to imports or the providers causes this error:

`Uncaught ReferenceError: __extends is not defined(…)`

If I click on the file where the error is occurring it shows this:

	var PropertyGroup = (function (_super) {
	    __extends(PropertyGroup, _super);   <<<this line
	    function PropertyGroup() {
	        _super.apply(this, arguments);
	        this.properties = null;
	    }
        ...etc

Am I missing something?

**Comment by ebrehault** [comment]
It looks like a more global Angular 2 issue, but I am not sure.
Could you paste your code in a Gist so we can have a look?

**Comment by jh-code** [comment]
I tried it on a fresh copy using the Angular CLI and I am getting the same error. So I am assuming the current version isn't compatible with the CLI? Another possibility I'm thinking is that my editor is using TS version 2.0.3. All I did was:

`ng new test-schema-form`
`cd test-schema-form`
`npm install angular2-schema-form --save-dev`
(imported SchemaFormModule, WidgetRegistry, DefaultWidgetRegistry and added them to the proper places in imports and providers)

**Comment by jh-code** [comment]
I just tried by cloning the repo and importing from `angular2-schema-form/src` and it seems to work fine. Not sure why it won't work with the npm package...

**Comment by ebrehault** [comment]
Just because we moved to Angular CLI 2 days ago and we haven't released on npm yet. Sorry for that, I publish it right now.

**Comment by CSchulz** [comment]
@ebrehault index.js isn't linked correctly. There is no dist folder anymore.

**Comment by ebrehault** [comment]
Woah, sorry again!
I will fix ASAP (I am attending a conference this week and the network is not that good, running NPM is very difficult, but I will do my best).

**Comment by ebrehault** [comment]
fixed in 1.0.0-alpha.31
