### ISSUE TITLE
Dont work in Windows 10 on "npm start"

### ISSUE THREAD

**Issue by Fresst10** [makinacorpus/angular2-schema-form#2]
![npm_start_in_windows10](https://cloud.githubusercontent.com/assets/20557044/17015226/a5fd3bd6-4f31-11e6-8b95-83675878865d.jpg)

**Comment by fbessou** [comment]
Case 1: You installed through npm
If you installed this package as a node module through npm, you can't run the start script. The npm version of this package is meant to be required by an application.
If you want to test this take a look at https://github.com/fbessou/angular2-schema-form-demo

Case 2: You have cloned from github
Your screenshot does not include the informative part of the message. A guess would be  that you have to set the environment variable `ENV_NODE` to `production` manually before calling `npm start`(or try to use a unix shell):
```bash
set NODE_ENV=production
```

**Note that currently this module (and angular 2) is currently unstable and should not be used in production code**

**Comment by Fresst10** [comment]
Sorrry. I tried to install "https://github.com/fbessou/angular2-schema-form-demo" on windows 10 and it failed. On ubuntu 16.04 it works. 
![angular2-schema-form-demo-windows10](https://cloud.githubusercontent.com/assets/20557044/17048857/d30a5634-4ff1-11e6-822d-76c291151ded.jpg)

**Comment by fbessou** [comment]
Seems like the port 3002 is already taken on your system. You can change it in `webpack.config.js` in the `devServer` section.

**Comment by Fresst10** [comment]
3002 is free. I tried on 3000.....it doesnt help. .Seems like the webpark-dev-server not compatible with windows.

**Comment by Fresst10** [comment]
Sorry, it was a problem with the port.

**Comment by fbessou** [comment]
Ok, I'm closing this issue then.

**Comment by Fresst10** [comment]
Ok, thx)
