### ISSUE TITLE
Request: Button ID

### ISSUE THREAD

**Issue by Sebastian-G** [makinacorpus/angular2-schema-form#22]
Hi can you please add a id or something else, for customizing abort / save buttons.
For different button styles. [Example](http://i.stack.imgur.com/gHqjT.png) 

PS. `1.0.0-alpha.29` breaks my build.
`[default] /home/sebastian/Dokumente/StuproGUI/app/src/app/app.module.ts:63:48 
    Cannot find module 'angular2-schema-form'.`

**Comment by CSchulz** [comment]
Missing index.ts in #19 tracked
