### ISSUE TITLE
Custom widget support

### ISSUE THREAD

**Issue by bombompb** [makinacorpus/angular2-schema-form#24]
After release: 1.0.0-alpha.24, the custom widget example (so called: "wizard") where you could page through the field-set's is not working anymore. In case you have a large json schema which you want to use in this control, then it becomes necessary from a UX perspective to be able to group/page/tab.....things (so as user you get the overview). Can you fix this in a newer release?

**Comment by ebrehault** [comment]
Definitely, we will.

**Comment by bombompb** [comment]
ok, cool. 

Any idea when we can expect this? thanks

**Comment by ebrehault** [comment]
I will do my best to have it fixed by next week.

**Comment by ebrehault** [comment]
Do not hesitate to ping me if nothing happen, as I might forget :)

**Comment by bombompb** [comment]
great, I will check in a week. 
thanks for the effort.

**Comment by ebrehault** [comment]
@fbessou actually I cannot find back this "wizard" feature, any hints? did you moved it into a separate add-on?

**Comment by fbessou** [comment]
The wizard widget was an example widget developped for the angular2-schema-form module :
You can find it here : https://github.com/fbessou/angular2-schema-form-demo/blob/master/src/app/wizard.widget.ts
I can extract it to its own module if you want.

**Comment by ebrehault** [comment]
@fbessou thanks for pointing me to the right place.

No I didn't mean to make it an actual module.
I will just test this example with the current version (and upgrade it as @bombompb mentioned it seems broken since alpha.24).

**Comment by bombompb** [comment]
ping ping, just checking in after a week. How is it going?

**Comment by ebrehault** [comment]
@bombompb sorry, I did not told you. @fbessou has upgraded https://github.com/fbessou/angular2-schema-form-demo (thanks @fbessou :) ), where you can see the "wizard" demo, and it works just fine with the current angular2-schema-form version.

**Comment by bombompb** [comment]
Thanks, this indeed resolved the issue.
