### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by estradamarkie** [makinacorpus/angular2-schema-form#25]
I followed the installation guide but its giving me a bunch of error therefore the project won't run. I did try installing the plugin again see if that works but clearly it didn't.

Any solution to this?

`ERROR in ./src/main.browser.ts
Module build failed: Error: Cannot resolve module 'angular2-schema-form' in C:\Users\mestrada\Desktop\schema-J                     SON\angular2-schema-form-demo-master\src
    Required in C:\Users\mestrada\Desktop\schema-JSON\angular2-schema-form-demo-master\src\main.browser.ts
    at ResolutionError.Error (native)
    at new ResolutionError (C:\Users\mestrada\Desktop\schema-JSON\angular2-schema-form-demo-master\node_module                     s\awesome-typescript-loader\dist.babel\deps.js:592:88)
    at C:\Users\mestrada\Desktop\schema-JSON\angular2-schema-form-demo-master\node_modules\awesome-typescript-                     loader\dist.babel\deps.js:400:37
    at run (C:\Users\mestrada\Desktop\schema-JSON\angular2-schema-form-demo-master\node_modules\core-js\module                     s\es6.promise.js:87:22)
    at C:\Users\mestrada\Desktop\schema-JSON\angular2-schema-form-demo-master\node_modules\core-js\modules\es6                     .promise.js:100:28
    at flush (C:\Users\mestrada\Desktop\schema-JSON\angular2-schema-form-demo-master\node_modules\core-js\modu                     les\_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

ERROR in [default] C:/Users/mestrada/Desktop/schema-JSON/angular2-schema-form-demo-master/node_modules/ng2sf-t                     inymce/dist/src/tinymce.widget.d.ts:1:30
Cannot find module 'angular2-schema-form'.

ERROR in [default] C:/Users/mestrada/Desktop/schema-JSON/angular2-schema-form-demo-master/src/app/app.componen                     t.ts:2:31
Cannot find module 'angular2-schema-form'.

ERROR in [default] C:/Users/mestrada/Desktop/schema-JSON/angular2-schema-form-demo-master/src/app/app.module.t                     s:8:7
Cannot find module 'angular2-schema-form'.

ERROR in [default] C:/Users/mestrada/Desktop/schema-JSON/angular2-schema-form-demo-master/src/app/wizard.widge                     t.ts:1:35
Cannot find module 'angular2-schema-form'.

ERROR in [default] C:/Users/mestrada/Desktop/schema-JSON/angular2-schema-form-demo-master/src/app/wizard.widge                     t.ts:43:37
Property 'schema' does not exist on type 'WizardWidget'.

ERROR in [default] C:/Users/mestrada/Desktop/schema-JSON/angular2-schema-form-demo-master/src/main.browser.ts:                     3:31
Cannot find module 'angular2-schema-form'.
`

**Comment by ebrehault** [comment]
sorry but the last release is broken, we will fix it ASAP

**Comment by estradamarkie** [comment]
@ebrehault Oh right hehe no worries, is there an estimated time of fix?

**Comment by ebrehault** [comment]
by next week hopefully

**Comment by estradamarkie** [comment]
Thanks :)

**Comment by ebrehault** [comment]
@estradamarkie it is fixed by the way

**Comment by estradamarkie** [comment]
@ebrehault Hi, I pulled your test repo for this project and still couldn't npm start it

`Failed at the angular2-schema-form-demo@1.0.0-alpha.2 start script 'npm run webpack-dev-server'.`

**Comment by ebrehault** [comment]
The demo module is not upgraded yet, we will do that soon.
