### ISSUE TITLE
Error when importing module in submodule

### ISSUE THREAD

**Issue by ce86** [makinacorpus/angular2-schema-form#26]
Hi,

I am receiving an error when trying to use the library in a submodule of my application:
EXCEPTION: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

As per http://stackoverflow.com/a/39414253 I assume that there should be CommonModule included instead of BrowserModule in your schema-form.module.ts.
(Do not import BrowserModule in any other module. Feature modules and lazy loaded modules should import CommonModule instead. They need the common directives. They don't need to re-install the app-wide providers.)

Is there a way around this problem or is this a bug?

I then tried to import the module in my main app.module.ts (not in my sub.module.ts) but then <schema-form [schema]="mySchema"></schema-form> is simply not rendered.
Can you maybe give me a hint?

Best regards

Chris

**Comment by fbessou** [comment]
Fixed by #27
