### ISSUE TITLE
angular2-schema-form 404 (Not Found)

### ISSUE THREAD

**Issue by janfriedli** [makinacorpus/angular2-schema-form#3]
When adding the FieldRegistryService at bootstrap i get the following error: 

`zone.js:101 GET http://localhost:4200/angular2-schema-form 404 (Not Found)`

I am using angular cli. 

```javascript
//main.ts
import { bootstrap } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { AppComponent, environment } from './app/';
import { HTTP_PROVIDERS } from '@angular/http';
import { appRouterProviders } from './app/app.routes';
import { FieldRegistryService } from "angular2-schema-form";

if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent, [appRouterProviders, HTTP_PROVIDERS, FieldRegistryService]);
```

Any idea what might be missing?

**Comment by fbessou** [comment]
I never experienced this issue but while angular 2 RC5 is not released you have to add the provideForms() and disableDeprecatedForm() providers to be able to use this library.

Have you installed angular2-schema-form with `npm` or `git clone` ?

**Comment by janfriedli** [comment]
Thx for the quick response.
I installed it trough npm as written in the README. The IDE is able to find the references...
Adding provideForms() and disableDeprecatedForm() didn't help.

**Comment by fbessou** [comment]
Any error/warning on `npm install` ?

**Comment by janfriedli** [comment]
Nope. But  I figured out that I had to add the following:
 ```javascript
// angular-cli-build.js -> vendorNpmFiles
'angular2-schema-form/dist/*.js'
```

After that run `ng build`. If this was successful you should find the files in `dist/angular2-schema-form`

Then make sure your `system-config.ts` looks like this:
 ```javascript
const map: any = {
  'angular2-schema-form': 'vendor/angular2-schema-form/dist'
};

/** User packages configuration. */
const packages: any = {
  'angular2-schema-form': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'index.js'
  },
};
 ```

If everything worked fine the 404 should be gone.

This issue can therefore be closed.

**Comment by fbessou** [comment]
Nice ! I have only tested with webpack yet. Thanks for giving us these steps.

**Comment by anupamarachuri** [comment]
Hi 

Could you please upload a sample of integration with angular 2 or some steps?
