### ISSUE TITLE
submit form and enum

### ISSUE THREAD

**Issue by estradamarkie** [makinacorpus/angular2-schema-form#32]
Is there a way to submit the form back to the server? Is there any way of binding the inputs?

Also does this support [enum]? something like this
`,
      "Status":{  
         "enum":[  
            "Preparing",
            "AwaitingCompletion",
            "Cancelled",
            "Completed"
         ],
         "type":"string"
      },`

Just hoping that the module would be something like this
http://brutusin.org/json-forms/#2

**Comment by ebrehault** [comment]
> Is there a way to submit the form back to the server?

Yes of course (that's basically what everybody would expect from a form lib, right :) ), you just need to implement an action for that.
If you consider the demo, here https://github.com/makinacorpus/angular2-schema-form/blob/master/demo/app.component.ts#L83 we define an action, which just does an alert, but it could also call the http service to post the data to a backend.

> Is there any way of binding the inputs?

the model is bound, so you do get the input values that way

> Also does this support [enum]?

we do not support the basic `enum` usage, we prefer `oneOf` as it allows to specify value/label pairs, example: https://github.com/makinacorpus/angular2-schema-form/blob/master/demo/sampleschema.json#L86

**Comment by estradamarkie** [comment]
Thanks, yeah ofc that's what everybody expect haha just didn't realise that the action button is within the schema as well. Just looked at the demo and seems pretty clear :) 

Model: do I need to use [model]=""?

Enum: I see, I don't think I will be able to change how the data is as its all coming from the back-end people and its all being generated by Swagger.

**Comment by ebrehault** [comment]
In your app, you are free to perform any changes on the data you receive from your backend.
So if your backend use regular `enum`, you can process it in your `subscribre()` to turn it into `oneOf` and then pass it to the schema-form component.
The same goes with `$ref`: you can read its value, resolve it to get the corresponding schema and inject it in the schema you pass to the form.

**Comment by marc101101** [comment]
@ebrehault is this demo still available somewhere? because the new demo is not containing this allert statement?

**Comment by marc101101** [comment]
**What I do:**
`<sf-form [schema]=config_json_schema.schema [model]=config_json_schema.model></sf-form>`
**What I want:**
I want the "changed" model back by clicking a submit button.

**Comment by ebrehault** [comment]
The demo has been moved in ./tests. The code you are talking about is here:
https://github.com/makinacorpus/angular2-schema-form/blob/master/tests/src/app/app.component.ts#L101.

I am not sure how you want to do it, but I would store the changed schema directly in this.config_json_schema.schema, so you can access anytime.
