### ISSUE TITLE
Subschema

### ISSUE THREAD

**Issue by Fresst10** [makinacorpus/angular2-schema-form#4]
Hello again) Could I use subschema in this module? If it possible, could you show an object example of schema?

**Comment by fbessou** [comment]
Subschema are currently not supported. Currently the only supported types are string, number/integer and boolean.
You could probably create a custom field type and its value accessor to be able to represent the subschema (maybe using itself a SchemaForm ).

**Comment by Fresst10** [comment]
Ok, thx) I hope in the next version it will be native)

**Comment by fbessou** [comment]
Maybe I have misunderstood what you were asking.
Do you want to be able to build a form from this kind of schema ?

```js
{
  "properties": {
    "name": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    }
  }
}

```
with `address` having its own subschema ?

**Comment by Fresst10** [comment]
Yes, I want create something like in this example - http://jspears.github.io/subschema/#/Loader?_k=4hk4x7. When I click on the button "Add", shows a new form.

**Comment by fbessou** [comment]
Ok, neither arrays nor subschema are supported yet but note that if you want to display a field conditionally, you can use the `showIf` property:

```js
"properties": {
  "name": {
    "type": "string"
  },
  "showAddress": {
    "type": "boolean"
  },
  "address": {
    "type": "string",
    "visibleIf": {"showAddress":[true]}
  }
}
```

**Comment by Fresst10** [comment]
I tried this json to test. It doesnt work. I want to see "street" in view. What I have written is not correct?. 
{
            "$schema": "http://json-schema.org/draft-04/hyper-schema#",
            "type": "object",
            "properties": {
            "firstName": {
              "type": "string",
                "placeholder": "First name",
                "minLength": 2,
                "maxLength": 40,
                "title": "First name",
                "description": "First name",
            },
            "inpBtn": {
              "type": "inputWithButton",
              "placeholder": "First name",
              "minLength": 2,
              "maxLength": 40,
              "title": "First name",
              "description": "First name",
            }, "address": {
                "type": "object",
                "properties": {
                  "street": {
                    "type": "string",
                    "placeholder": "Street",
                    "title": "Street",
                    "description": "Street"
                  },
                  "city": {
                    "type": "string"
                  },
                  "zip": {
                    "type": "string"
                  }
                },
                "fieldsets":[{
                  "id": "part_2",
                  "fields":[ "street"]
                }],
                "required": ["street"]
            }
          },
          "fieldsets":[{
            "id": "part_1",
            "fields":[ "firstName","inpBtn", "address"]
          }],
          "required": []
        };

**Comment by Fresst10** [comment]
Thx) I am very need in subschema for my project)

**Comment by fbessou** [comment]
As I previously said, currently nested schemas are not implemented.
You have to flatten your schema and can use fieldsets to visually organise your data.
```js
{
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string",
			"placeholder": "First name",
			"minLength": 2,
			"maxLength": 40,
			"title": "First name",
			"description": "First name"
		},
		"inpBtn": {
			"type": "inputWithButton",
			"placeholder": "First name",
			"minLength": 2,
			"maxLength": 40,
			"title": "First name",
			"description": "First name"
		}, 
		"street": {
			"type": "string",
			"placeholder": "Street",
			"title": "Street",
			"description": "Street"
		},
		"city": {
			"type": "string"
		},
		"zip": {
			"type": "string"
		}
	},
	"fieldsets":[{
		"id": "info",
		"fields":[ "firstName","inpBtn"]
	},{
		"id": "address",
		"fields":[ "street", "city", "zip"]
	}],
	"required": ["street"]
}
```

**Comment by Fresst10** [comment]
Yes, thx) I incorrectly translated  your phrase))

**Comment by fbessou** [comment]
Subschemas are supported.
