### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by kalakuriphani** [makinacorpus/angular2-schema-form#41]
Hi,
While I am trying to upload image file, the json value is coming null.
I am using the below in the json schema. Can you please advise.

    "image":{
      "type":"string",
      "widget":"file",
      "media": {
        "binaryEncoding": "base64",
        "type": "image/*"

      }

**Comment by ysyyork** [comment]
any updates on this? I met the same issue

**Comment by ludcl** [comment]
Any workarround on this at least?
