### ISSUE TITLE
A suggestion for  collaboration

### ISSUE THREAD

**Issue by AlmogShaul** [makinacorpus/angular2-schema-form#44]
Hi,
We would like to collaborate and contribute to your project.
We have ideas to enrich the form capabilities.
Are you interested?

Shaul Almog
Sapiens Technologies

**Comment by ebrehault** [comment]
Hi @AlmogShaul,

Sure, any contribution is welcome!!
I think the best to discuss new ideas is to use GitHub issues if you are ok with that.

**Comment by AlmogShaul** [comment]
Great!
