### ISSUE TITLE
TinyMCE cannot load its plugins

### ISSUE THREAD

**Issue by ebrehault** [makinacorpus/angular2-schema-form#6]
When I add a 'richtext' field in my schema, I get an error:
`Failed to load: /node_modules/tinymce/plugins/code/plugin.js`

**Comment by fbessou** [comment]
Angular2 Schema Form does not depend on tinymce anymore.
If you want to use the tinymce, use the [ng2sf-tinymce](https://github.com/fbessou/ng2sf-tinymce) npm package.
