### ISSUE TITLE
EXCEPTION: Parsing error on /Profiles/: No 'items' property in array

### ISSUE THREAD

**Issue by YoYo35** [makinacorpus/angular2-schema-form#62]
I tryed to use object with array property and got error:

> Parsing error on /Profiles/: No 'items' property in array

Profiles is array property. In json its look like ""Profiles":["A", "B"]". 

How can I fix it?
My schema is:
this.mySchema = {      
        "Profiles": {
          "type": "array",
          "widget": "array",
        }
      }

**Comment by fbessou** [comment]
you have to add the schema of your items:
````js
this.mySchema = {
  "properties": {
    "Profiles": {
      "type": "array",
      "widget": "array",
      "items": {
        "type": "string"
      }
    }
  }
}
```

**Comment by YoYo35** [comment]
Yes, it's working! Thank you.
