### ISSUE TITLE
Handle actions on buttons

### ISSUE THREAD

**Issue by zolekm** [makinacorpus/angular2-schema-form#63]
Hi,

i'm trying to handle action from button in my class function. The Problem is i can't define function which will handle action, i can only define object with function where word "this" is lost. I have hard time to get this work but i'm not seeing any workaround for this can anyone help me with this?

Any help is welcome

Thanks, Matija

**Comment by schmuli** [comment]
when you define your actions, use a lambda function, which will keep the `this`:

```javascript
this.actions = {
    send: () => {
         // `this` will be the containing class
    }
};
```

**Comment by zolekm** [comment]
@schmuli tnx for reply it works
