### ISSUE TITLE
Error when creating widget.

### ISSUE THREAD

**Issue by davidsennekool** [makinacorpus/angular2-schema-form#72]
When trying to import StringWidget (or any other widget) it gives me an error: `Type 'any' is not a constructor function type.` on the last line.

```typescript
import { Component } from '@angular/core';
import { StringWidget } from 'angular2-schema-form';

@Component({
  selector: 'mdl-sf-string-widget',
  templateUrl: './string.widget.html'
})

export class MyStringWidget extends StringWidget {}
```

How should I resolve this error?

**Comment by ebrehault** [comment]
Here is a working example https://github.com/ebrehault/ng-sf-mdl-demo

I would be curious to know what was wrong in your case (so I can update the doc).

**Comment by davidsennekool** [comment]
Yes. After importing the default widgets like that, the error is gone. But now I get another error: `Cannot find name 'require'` on this line: `let ZSchema = require('z-schema');`.

I did try to install requirejs through node, but that doesn't seem to work either.

**Comment by fbessou** [comment]
Which command are you using to build your angular project ?

**Comment by davidsennekool** [comment]
I used `ng build` to build the project... It gives me two exact same errors: `Cannot find name 'require'.`

**Comment by fbessou** [comment]
Try installing @types/node :
npm install @types/node --save-dev

**Comment by davidsennekool** [comment]
Still the same two errors...

**Comment by ebrehault** [comment]
Add `declare var require: any;` in your src/typings.d.ts and the compiler should be happy.

**Comment by davidsennekool** [comment]
It's working! Thanks a lot 😄
