### ISSUE TITLE
multiple radio button groups

### ISSUE THREAD

**Issue by VitaliiZhukov** [makinacorpus/angular2-schema-form#75]
Hi!
Could you please provide an example of scheme with multiple radio button groups?
The thing is that if I define few properties fields with widget="radio" then they behave as like as all the radiobuttons are within one radiogroup (I select a radiobutton => selecting from another group disappears)
I tried to provide fieldsets for different radiogroups but it didn't work
Thanks!

**Comment by Gundarf** [comment]
Hello,

I had the same problem. I patched my fork :
https://github.com/Gundarf/angular2-schema-form/blob/master/src/defaultwidgets/radio/radio.widget.ts

**Comment by VitaliiZhukov** [comment]
Hi!
Thank you! I also came up to this solution and implemented widget (using material-ui radio buttons)

Really weird buttons behaviour cause all of them are in different fieldsets and have appropriate names.
