### ISSUE TITLE
Ng4 support

### ISSUE THREAD

**Issue by heppy83** [makinacorpus/angular2-schema-form#82]
Hi... 
not sure this is the best to place to ask but...

Is this module usable with Angular4? Do you have any plan to shift to this version any soon?
Thank you!

**Comment by ZheyangSong** [comment]
@heppy83 AFAIK, Angular4 is backwards-compatible. There should be nothing stopping an Angular2 component from working. I think the owner of this project should upgrade the peerDep.

**Comment by i-am-dror** [comment]
I get the error below after upgrading to 4 but after webpack's reload it's working fine. 

ERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported functi
on, resolving symbol ANALYZE_FOR_ENTRY_COMPONENTS in /Users/drorrash/work/side/ngMaterialApp/node_modules/angular2-json-schema-form/node_modules/@angular/core/core.d.ts, resolving symbol JsonSchemaFormModule.forR
oot in /Users/drorrash/work/side/ngMaterialApp/node_modules/angular2-json-schema-form/src/library/json-schema-form.module.ts, resolving symbol AppModule in /Users/drorrash/work/side/ngMaterialApp/src/app/app.modu
le.ts, resolving symbol AppModule in /Users/drorrash/work/side/ngMaterialApp/src/app/app.module.ts

**Comment by the-ult** [comment]
Would stil be nice if all dependencies  are updated to the current versions.

**Comment by ebrehault** [comment]
As stated by @ZheyangSong , it works on Angular 4, but, yes, we do plan to release an updated version soon.
