### ISSUE TITLE
Changing schema after form instanciation

### ISSUE THREAD

**Issue by ebrehault** [makinacorpus/angular2-schema-form#85]
Changing schema after form instanciation seems to be broken.
In my last commit (https://github.com/makinacorpus/angular2-schema-form/commit/389691ea346be2eab6b416f4147911b6067161dd) I have add a very basic example, when we click the button, it update the schema, but the form is not refreshed.
The `ngOnChange` is triggered but something somewhere goes wrong.
I spent some time on it but I cannot find the reason, I think I am missing something obvious. @fbessou, any idea?

**Comment by ZheyangSong** [comment]
I'm facing the same issue. Though the schema is updated, the view is not re-rendered. My schema is pass in as an observable and subscribed using `async` pipe.

**Comment by ebrehault** [comment]
Fixed by #86
