### ISSUE TITLE
Add default widget  Property?

### ISSUE THREAD

**Issue by qwe852147** [makinacorpus/angular2-schema-form#89]
Can add default widget property example  ID and classname?

**Comment by ebrehault** [comment]
I am not sure I understand your question, but if you refer to this issue https://github.com/makinacorpus/angular2-schema-form/issues/87, it is fixed now.

**Comment by qwe852147** [comment]
It possible  add ID and className to set  element ID and className Property in schema json

**Comment by ebrehault** [comment]
By default no, but you can customize your widget templates to achieve that.

**Comment by qwe852147** [comment]
Thanks!
