### ISSUE TITLE
Validation String / int 

### ISSUE THREAD

**Issue by marc101101** [makinacorpus/angular2-schema-form#90]
Hello,

is there a basic validation of strings and ints implemented?

> The code above creates a form with three required fields. The validation state of each field is reflected by the class of each of them which can be either "has-error" or "has-success". Validation is done everytime a field's value changes. Basic validation is made by testing the value of the field against its corresponding schema.

When is this "has-error" getting triggered?
Really looking forward to your answer - markus

**Comment by ebrehault** [comment]
Actually it used to be part of the form template, but we removed it.
I have just restored it in formelement.
