### ISSUE TITLE
Validation returns Error Message

### ISSUE THREAD

**Issue by marc101101** [makinacorpus/angular2-schema-form#95]
Is the feature "Validation returns Error Message" planned? 
**Example - Schema:**
```
[...]
"password": {
      "type": "string",
      "title": "Password",
      "minLength": 3,
      "maxLength": 10
    }
[...]
```
**Example - Error Message:**
Password
•••••••••••
does not meet maximum length of 10
Hint: Make it strong!

**Comment by marc101101** [comment]
okay i got a further: 
`var err = _this.zschema.getLastErrors();`
returns error array with objects which contain the error message

**Comment by marc101101** [comment]
@ebrehault what is your adivce to show an Error Message:
MIN_LENGTH : String is too short (0 chars), minimum 5 (example)
- which i get from z-schema

**Comment by ebrehault** [comment]
Well, it should be the responsibility of the widget to render error messages.
